services:
  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_DB: llm-playground
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3001:8000"
    environment:
      - PYTHONUNBUFFERED=1
    # volumes:
    #   - ./backend/app:/app/app
    networks:
      - app-network
    depends_on:
      - db
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: