"""add anthropic models

Revision ID: 1c9c41905fb6
Revises: 9f8267078ed8
Create Date: 2024-09-30 17:31:08.813255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c9c41905fb6'
down_revision: Union[str, None] = '9f8267078ed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    op.execute('alter type modelapi add value \'ANTHROPIC\'')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    op.execute('alter type modelapi drop value \'ANTHROPIC\'')
