"""change message content to json

Revision ID: 2e992f3f46ab
Revises: 63e93b6411a7
Create Date: 2024-10-13 12:49:27.059282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e992f3f46ab'
down_revision: Union[str, None] = '63e93b6411a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message_content', 'content',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               postgresql_using="to_jsonb(content)::json",
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message_content', 'content',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
