"""support multiple types of message contents

Revision ID: 44c8787a686e
Revises: 89ecbbadfb7d
Create Date: 2024-10-08 15:19:46.317647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44c8787a686e'
down_revision: Union[str, None] = '89ecbbadfb7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('TEXT', 'IMAGE', name='messagecontenttype'), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('image_type', sa.String(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # before dropping the column, migrate existing message content (from the content column of the Message table) to the new table
    # every entry will just have type TEXT and content equal to the old content
    # with image_type null and order 0
    op.execute('''
        INSERT INTO message_content (id, type, content, message_id, "order")
        SELECT gen_random_uuid(), 'TEXT', content, id, 0
        FROM message
    ''')
    op.drop_column('message', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.execute('''
        UPDATE message
        SET content = (
            SELECT content
            FROM message_content
            WHERE message_content.message_id = message.id
            AND message_content.order = 0
            AND message_content.type = 'TEXT'
        )
    ''') # migrate the content back to the message table, only the TEXT type content since we no longer have the IMAGE type
    op.drop_table('message_content')
    # ### end Alembic commands ###
