"""update messagecontenttype to support files

Revision ID: 62424a42f230
Revises: efb6323bdebc
Create Date: 2024-11-06 15:20:13.037764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62424a42f230'
down_revision: Union[str, None] = 'efb6323bdebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''ALTER TYPE messagecontenttype ADD VALUE 'FILE' ''')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
        UPDATE message_content
        SET type = 'TEXT'
        WHERE type = 'FILE'
    ''')
    op.execute('''ALTER TYPE messagecontenttype DROP VALUE 'FILE' ''')
    # ### end Alembic commands ###
