"""add model field to chat and message

Revision ID: b7c32cfe7f81
Revises: eda3e68cbaec
Create Date: 2024-09-18 16:51:48.953185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7c32cfe7f81'
down_revision: Union[str, None] = 'eda3e68cbaec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('default_model', sa.String(), nullable=False, server_default='gpt-4o-mini'))
    op.alter_column('chat', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chat', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('message', sa.Column('model', sa.String(), nullable=True, server_default='gpt-4o-mini'))
    op.alter_column('message', 'role',
               existing_type=postgresql.ENUM('USER', 'ASSISTANT', 'SYSTEM', name='role'),
               nullable=False)
    op.alter_column('message', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('message', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('message', 'chat_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('message', 'chat_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('message', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('message', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('message', 'role',
               existing_type=postgresql.ENUM('USER', 'ASSISTANT', 'SYSTEM', name='role'),
               nullable=True)
    op.drop_column('message', 'model')
    op.alter_column('chat', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('chat', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('chat', 'default_model')
    # ### end Alembic commands ###
