"""update api key to use string for provider

Revision ID: efb6323bdebc
Revises: e03da1cbd4ef
Create Date: 2024-10-22 14:36:04.000606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efb6323bdebc'
down_revision: Union[str, None] = 'e03da1cbd4ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_key', 'provider',
               existing_type=postgresql.ENUM('OPENAI', 'ANTHROPIC', name='modelapi'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_key', 'provider',
               existing_type=sa.String(),
               type_=postgresql.ENUM('OPENAI', 'ANTHROPIC', name='modelapi'),
               existing_nullable=False)
    # ### end Alembic commands ###
