"""add created_at to message and chat

Revision ID: d5f467d53b88
Revises: b7c32cfe7f81
Create Date: 2024-09-19 13:45:26.067254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5f467d53b88'
down_revision: Union[str, None] = 'b7c32cfe7f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('message', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'created_at')
    op.drop_column('chat', 'created_at')
    # ### end Alembic commands ###
