"""Update role column type

Revision ID: eda3e68cbaec
Revises: 14f962ab298f
Create Date: 2024-09-17 15:13:52.435319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from schemas import Role


# revision identifiers, used by Alembic.
revision: str = 'eda3e68cbaec'
down_revision: Union[str, None] = '14f962ab298f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    role = postgresql.ENUM(Role, name='role')
    role.create(op.get_bind(), checkfirst=True)
    op.execute('ALTER TABLE message ALTER COLUMN role TYPE role USING role::text::role')
    # op.alter_column('message', 'role',
    #            existing_type=sa.VARCHAR(),
    #            type_=role,
    #            existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    role = postgresql.ENUM(Role, name='role')
    # op.alter_column('message', 'role',
    #            existing_type=role,
    #            type_=sa.VARCHAR(),
    #            existing_nullable=True)
    op.execute('ALTER TABLE message ALTER COLUMN role TYPE VARCHAR USING role::text')
    role.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
